version: "3.3"

services:

  traefik:
    image: "traefik:v3.1"
    command:
      # - "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    command_for_tls:
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.websecure.address=:443"
      - "--providers.file.directory=/traefik/config/dynamic_conf"
    ports:
      - "80:80"
      # - "8080:8080"
    ports_for_tls:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_for_tls:
      - "./tls:/traefik/config/tls:ro"
      - "./tls_traefik_config.yml:/traefik/config/dynamic_conf/tls_traefik_config.yml:ro"
    networks:
      - traefik

  project_container_prototype:
    networks:
      - traefik
    labels:
      - "traefik.docker.network=${current_project_name}_traefik"
      - "traefik.http.routers.${sub_folder}.rule=Host(`${fqdn}`)"
      - "traefik.http.services.${sub_folder}.loadbalancer.server.port=80"
    labels_for_tls:
      - "traefik.http.routers.${sub_folder}.entrypoints=websecure"
      - "traefik.http.routers.${sub_folder}.tls=true"

networks:
  traefik:
    internal: false