tls:
  certificates:
    - certFile: /traefik/config/tls/domainA.crt
      keyFile: /traefik/config/tls/domainA.key
    - certFile: /traefik/config/tls/domainB.crt
      keyFile: /traefik/config/tls/domainB.key
  stores:
    default:
      defaultCertificate:
        certFile: /traefik/config/tls/default.crt
        keyFile: /traefik/config/tls/default.key
